import type { Vehicle, Checklist } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    plate: 'ABC-1234',
    model: 'Fiat Fiorino',
    driver: 'João Silva',
    status: 'Operacional',
    fuelLevel: 80,
    odometer: 123456,
    image: 'https://picsum.photos/seed/van1/400/300',
    lastCheck: '2024-07-28',
  },
  {
    id: '2',
    plate: 'DEF-5678',
    model: 'Renault Kangoo',
    driver: 'Maria Oliveira',
    status: 'Com Problemas',
    fuelLevel: 30,
    odometer: 98765,
    image: 'https://picsum.photos/seed/van2/400/300',
    lastCheck: '2024-07-28',
  },
  {
    id: '3',
    plate: 'GHI-9012',
    model: 'Peugeot Partner',
    driver: 'Carlos Pereira',
    status: 'Manutenção',
    fuelLevel: 100,
    odometer: 250000,
    image: 'https://picsum.photos/seed/van3/400/300',
    lastCheck: '2024-07-27',
  },
  {
    id: '4',
    plate: 'JKL-3456',
    model: 'Fiat Fiorino',
    driver: 'Ana Costa',
    status: 'Operacional',
    fuelLevel: 65,
    odometer: 180123,
    image: 'https://picsum.photos/seed/van4/400/300',
    lastCheck: '2024-07-28',
  },
];

export const checklists: Checklist[] = [
  {
    id: 'c1',
    vehicleId: '2',
    driver: 'Maria Oliveira',
    type: 'Saída',
    date: '2024-07-28',
    time: '08:00',
    odometer: 98700,
    fuelLevel: 50,
    items: {
      farol_esquerdo: 'ok',
      farol_direito: 'issue',
      pisca_esquerdo: 'ok',
      buzina: 'ok',
      cintos_seguranca: 'ok',
      nivel_oleo_motor: 'ok',
    },
    notes: 'Farol direito não está funcionando.',
  },
  {
    id: 'c2',
    vehicleId: '1',
    driver: 'João Silva',
    type: 'Retorno',
    date: '2024-07-28',
    time: '18:30',
    odometer: 123456,
    fuelLevel: 80,
    items: {
      farol_esquerdo: 'ok',
      farol_direito: 'ok',
      pisca_esquerdo: 'ok',
      buzina: 'ok',
      cintos_seguranca: 'ok',
      nivel_oleo_motor: 'ok',
    },
    notes: 'Tudo certo.',
  },
  {
    id: 'c3',
    vehicleId: '3',
    driver: 'Carlos Pereira',
    type: 'Saída',
    date: '2024-07-27',
    time: '09:00',
    odometer: 249800,
    fuelLevel: 100,
    items: {
      nivel_oleo_motor: 'issue',
      farol_esquerdo: 'ok',
      farol_direito: 'ok',
    },
    notes: 'Nível de óleo do motor baixo. Precisa verificar.',
  },
];
